### ISSUE TITLE
boilerplate templates -- we have some contributing and license already

### ISSUE THREAD

**Issue by wseltzer** [w3c/w3c.github.io#11]
Are we duplicating what's in https://github.com/w3c/licenses ?  Those (contributing, license) should be the basis for new CG or WG repos.

**Comment by tripu** [comment]
My bad, @wseltzer&nbsp;&mdash;&nbsp;I didn't realise having licence templates here would be redundant.
Addressed in #12.

**Comment by wseltzer** [comment]
Thanks.
