### ISSUE TITLE
redundant spec labels?

### ISSUE THREAD

**Issue by chaals** [w3c/w3c.github.io#22]
I don't understand the difference between substantive and bug. Also, all changes are presumably enhancements, so I'm not sure what the purpose of that is, and it lacks clarity on whether it means editorial or substantive change.

**Comment by tripu** [comment]
For me, a `bug` is something that is broken, while an `enhancement` is an aspect that works but could/should be improved. Yes, every change is an enhancement, in some way (or you wouldn't make it) but I think that's a common convention.

And `substantive` and `bug` aren't exclusive, I think: bugs can be trivial, substantive, catastrophic&hellip; And enhancements, too.

**Comment by chaals** [comment]
@tripu 
> For me, a bug is something that is broken, while an enhancement is an aspect that works but could/should be improved.

Fair enough. Can we have slightly more explicit labels, given that there isn't any documentation in the issues system of github? Or should we just document the labels somewhere for the first time people are looking at them? (Hello maintenance)

**Comment by tripu** [comment]
I guess we could be more specific on [`https://w3c.github.io/spec-labels.html`](https://w3c.github.io/spec-labels.html), yes. Although for me that suffices as a general recommendation: groups end up with their own conventions, and the exact meaning of labels will vary depending on the nature of the repo, etc.

**Comment by tripu** [comment]
@plehegar, I'd close this one when #34 is merged

**Comment by tripu** [comment]
I propose we close this one now.
