### ISSUE TITLE
missing spec-label

### ISSUE THREAD

**Issue by chaals** [w3c/w3c.github.io#23]
In implementation, there are a number of cases where there *is* implementation but it isn't interoperable. At least in HTML I have found it very useful to have a label specifically for this.

**Comment by chaals** [comment]
Also, I prefer to use invalid for something where there is nothing to do here - no real bug, and be able to declare out-of-scope more explicitly, e.g. so another spec can pick it up.

For the same reason, having a generic tag for review from someone else can be helpful , where there is no specific label for the group in question.

**Comment by tripu** [comment]
Looks good to me, more so if it comes from experience :)

I think that in case of doubt we can use
*labels<sub>plh</sub> ∪ labels<sub>chaals</sub>*
to suit all needs.

**Comment by chaals** [comment]
I added most of the tags we have for HTML, which is the repo where I thought most about labels.

**Comment by plehegar** [comment]
I'm worried about the labels overly complicated here. I do think it's fine for a group to add more labels if needed. Imho, the most important labels are the horizontal ones.

**Comment by chaals** [comment]
It depends on the point of this process. I had understood that the idea was that we should use these labels - reducing our own labels to whatever this set becomes.

Personally, I think that's a non-starter, so if this is just a set of common labels for common tasks, which should be extended by whoever manages each individual repo, I think we have a reasonable set.

**Comment by tripu** [comment]
Yes, I also think whatever appears on [`w3c.github.io/spec-labels.html`](https://w3c.github.io/spec-labels.html) is just a baseline or a recommendation, and that groups should be free to extend that set in any way they feel is useful for them.

**Comment by plehegar** [comment]
let's see if the current set is common enough.
