### ISSUE TITLE
Merge sandhawke/spec-labels-min

### ISSUE THREAD

**Issue by jyasskin** [w3c/w3c.github.io#29]
Per https://github.com/w3c/w3c.github.io/pull/27#issuecomment-300105485, we should try to merge @sandhawke's [proposed spec labels](https://github.com/sandhawke/spec-labels-min) into this repository. I'm in favor of rewriting them to lowercase-with-dashes per #25 in the process.

**Comment by tripu** [comment]
Do @jyasskin or @sandhawke want to give it a go at merging their respective suggested label and colour sets, so that we can close #25, #27 and this one?

**Comment by plehegar** [comment]
@tmichel07 , can you send a proposal that merges what ttml is doing and what Sandro did?

**Comment by tmichel07** [comment]
The Timed Text WG has also elaborated labels to track Wide Review comments for TTML2 spec
Here is our proposal for Wide Review labels in github (Proposed Github labels are written into square brakets)

1- Processing comment within the TTWG
1.1- Comment received, not yet processed by the TTWG  [WR-open]
1.2- Discussed but pending TTWG  resolution,          [WR-pending]
1.3- Done - TTWG  resolution, (approved by WG)        [WR-resolved]
1.4- Done - TTWG  resolution and spec update          [WR-spec-updated]
1.5- Done with Partial TTWG  resolution (partially approved by WG),  [WR-resolved-partial]
1.6- Done with Partial TTWG  resolution and spec update  [WR-spec-updated-partial]
1.7- Done but comment Rejected                        [WR-rejected]

For each comment, the WG also fill a"type" :
 a-typo, b-editorial, c-substantive, d-general, e-undefined.

Once the TTWG has processed all comments, the next steps are to get approval from the commenter
2.1- Response drafted by WG              [WR-response-drafted]
2.2- Response send to commenter      [WR-response-sent]
2.3- Response agreed by commenter  [WR-commenter-agreed]
2.4- Response rejected by commenter  (need more discussion - back to step 1.5 or closing)  [WR-commenter-rejected]
2.6- Response partially agreed by commenter (need more discussion - back to step 1.5 or closing)  [WR-commenter-agreed-partial]
2.7- No Response received from commenter within the stated period [WR-commenter-noresponse]

For more information see ou wiki page
https://www.w3.org/wiki/TimedText/TTML2_Wide_Review

**Comment by tripu** [comment]
I personally find these labels used by the TT WG too {complex, specific, verbose}.

Given that we have by now [a large set of well-defined labels](https://w3c.github.io/issue-metadata.html), I'd stick with those and close this issue.

**Comment by plehegar** [comment]
The current set is a good start. Let's see later if we need to extend them.
