### ISSUE TITLE
Specify label colors

### ISSUE THREAD

**Issue by jyasskin** [w3c/w3c.github.io#30]
Per https://github.com/w3c/w3c.github.io/pull/27#issuecomment-300093439, Github labels each have a color, and we should specify that for the labels here, so that issues are visually consistent across repositories.

**Comment by plehegar** [comment]
https://w3c.github.io/hr-labels.json has color information for the horizontal labels.

eg.
  https://www.w3.org/2019/10/i18n-labels.html?gtype=working

**Comment by hober** [comment]
> https://w3c.github.io/hr-labels.json has color information for the horizontal labels.

Yes, but they're not listed on here: https://w3c.github.io/issue-metadata.html

**Comment by plehegar** [comment]
The colors are directly used on that page but I can add the color value in the text content as well.

**Comment by hober** [comment]
> The colors are directly used on that page but I can add the color value in the text content as well.

Great, thanks!
