### ISSUE TITLE
Remove generated or src files

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/w3c.github.io#38]
Can we remove the generated files from the repo? I noticed lots of people (including me) ended up editing the wrong files 😡. Alternatively, let's get rid of the src files - this simple site shouldn't need a build step.

**Comment by sideshowbarker** [comment]
We should remove the `.src` files and the build script and just manually maintaining the `.html` files. The build is overkill.

**Comment by marcoscaceres** [comment]
Agree... PR sent.
