### ISSUE TITLE
index.html should include direct link / explanation to ashkenz ashkenaz askenaz askenz ash-nazg

### ISSUE THREAD

**Issue by tantek** [w3c/w3c.github.io#42]
index.html should include a direct link to https://github.com/w3c/ash-nazg because it is totally unfindable otherwise 

(hence various misspellings / misspeakings of it included in issue name in order to increase websearch findability)

**Comment by marcoscaceres** [comment]
I’ve also raised concerns about the name previously, despite its nerdy origins (which I only learned about by Googling for it... 🤓).

**Comment by tripu** [comment]
&ldquo;Contributor management&rdquo; and &ldquo;IPR&rdquo; are mentioned on the front page. And [the corresponding page](https://w3c.github.io/repo-management.html) links to the GH project for the Repository Manager at the bottom.

@tantek, I guess you want a link to [the instance of the tool in production](https://labs.w3.org/hatchery/repo-manager/) (not to the source code) on that front page? (I'm okay with that.)

(About the name, I think it was kind of decided months ago that we'd use &ldquo;repository manager&rdquo; by default, for simplicity; and keep &ldquo;Ash-Nazg&rdquo; internal and for the GitHub repository only. So hopefully nobody needs to remember that name, except us few maintaining the tool&hellip;)

**Comment by plehegar** [comment]
(side comment: we need a page that lists all of the tools that are working on top of GH. ash-nazg, github-notify-ml, pr-review, travis, magic checkers from dom, ...). And link to the tooling page from @LJWatson .

**Comment by plehegar** [comment]
https://www.w3.org/wiki/AB/Tooling

**Comment by tripu** [comment]
Closing this because as I said we're linking to [`github.com/w3c/ash-nazg`](https://github.com/w3c/ash-nazg) from [`w3c.github.io/repo-management.html`](https://w3c.github.io/repo-management.html) already, and to [`labs.w3.org/repo-manager/`](https://labs.w3.org/repo-manager/) from several other pages (and I just updated https://www.w3.org/wiki/AB/Tooling with this and other URLs).
