### ISSUE TITLE
Framing of "W3C projects"

### ISSUE THREAD

**Issue by koalie** [w3c/w3c.github.io#5]
I read http://w3c.github.io/ and found that it lacked a clear policy on breadth of W3C Projects. 

If that is indeed the case, we should clarify that W3C Projects include W3C staff selected projects as well as W3C Working (Interest) Group projects. 

It is possible that we may want to assess other group's requests to host a given repository. For that, but also regardless, we should identify the owner(s) either by name or by e-mail address.

A specific concern of mine is that W3C Community Groups might expect we create repositories under the W3C organisation on GH. We have >220 CGs; that would hardly scale.

**Comment by tripu** [comment]
Anyone want to suggest some copy to add?

**Comment by koalie** [comment]
Gosh, I had forgotten that I opened this issue last year, although a bell rang faintly when I wrote the guidebook section on [W3C Team support for W3C Community Groups](https://www.w3.org/2016/04/cg-support/) which includes (emphasis mine):
>On approval of a W3C Domain Lead, W3C Community Groups can get WebEx and *Github resources from W3C*. That Domain lead is responsible for tracking and scheduling those resources.

Maybe one way to address issue #5 resides in this new section from the Guidebook?

**Comment by pswan004** [comment]
> I read http://w3c.github.io/ and found that it lacked a clear policy on breadth of W3C Projects.
> 
> If that is indeed the case, we should clarify that W3C Projects include W3C staff selected projects as well as W3C Working (Interest) Group projects.
> 
> It is possible that we may want to assess other group's requests to host a given repository. For that, but also regardless, we should identify the owner(s) either by name or by e-mail address.
> 
> A specific concern of mine is that W3C Community Groups might expect we create repositories under the W3C organisation on GH. We have >220 CGs; that would hardly scale.

**Comment by pswan004** [comment]
> Gosh, I had forgotten that I opened this issue last year, although a bell rang faintly when I wrote the guidebook section on [W3C Team support for W3C Community Groups](https://www.w3.org/2016/04/cg-support/) which includes (emphasis mine):
> 
> > On approval of a W3C Domain Lead, W3C Community Groups can get WebEx and _Github resources from W3C_. That Domain lead is responsible for tracking and scheduling those resources.
> 
> Maybe one way to address issue #5 resides in this new section from the Guidebook?
