### ISSUE TITLE
Information/docs on the W3C API is very hard to find (https://api.w3.org/doc)

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/w3c.github.io#88]
From browsing or searching the https://www.w3.org/ website, there does not seem to be any way to find any information about the W3C API. It’s not discoverable. It’s not even readily findable using Google Search or other search engines.

There should be some much-easier way to help people find information about the API.

**Comment by deniak** [comment]
One idea is to serve the [documentation](https://w3c.github.io/w3c-api/) on https://api.w3.org/ and display that link on all the public pages where we can find the data (/TR, WG pages, dashboards, etc) so people will know that the API exists.
It should also improve the ranking and be easier to find it from the different search engines

**Comment by sideshowbarker** [comment]
As part of a solution, one simple thing we could consider is making http://w3.org/api/ and http://w3.org/API/ be something other than 404. Maybe we could simply make them redirect to https://api.w3.org/ transclude (by Rewrite, I guess) the existing docs from https://w3c.github.io/w3c-api/ and/or https://api.w3.org/doc.

**Comment by deniak** [comment]
https://www.w3.org/api/ now redirects to the API doc under GH. This should be a good starting point for anyone who's interested in our API.
That link now also appears on the homepage, /TR and the new group pages. Hopefully, this should help people find the API and the link should become the top result on the different search engines.

**Comment by sideshowbarker** [comment]
Thanks much
